# Generated by Django 6.0.3 on 2026-04-05 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=15)),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_records',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['date'], name='financial_r_date_c7ef46_idx'), models.Index(fields=['type'], name='financial_r_type_161a00_idx'), models.Index(fields=['category'], name='financial_r_categor_2871f2_idx'), models.Index(fields=['status'], name='financial_r_status_3bddf3_idx'), models.Index(fields=['created_by'], name='financial_r_created_63a7c0_idx'), models.Index(fields=['reference_number'], name='financial_r_referen_4a393e_idx')],
            },
        ),
    ]
